### ISSUE TITLE
Adding IAM controls

### ISSUE THREAD

**Issue by gary-beautypie** [uswitch/terraform-provider-segment#33]
hey, are there any plans to add things like IAM roles or anything else from the API? Looks pretty awesome so far!

**Comment by agouil** [comment]
Hey, there are plans to add Function management to the provider but not IAM roles at the moment. You are welcome to raise a PR with the IAM roles changes though 😃

**Comment by kurt-lu** [comment]
We recently added support for Public API, including IAM.  Check out Segment's provider! https://registry.terraform.io/providers/segmentio/segment/0.2.0
