### ISSUE TITLE
Support for public API

### ISSUE THREAD

**Issue by singhalss** [uswitch/terraform-provider-segment#40]
Hi team,

I am trying to make use of this provider for segment IaC and looks like it is still using old config API instead of new public API. I am getting a HTTP/1.1 403 Forbidden error using this provider even though my access token is having right permissions (tested via public API and works fine).

Segment Public vs Config APIs documentation - https://segment.com/docs/api/public-api/.

Are there any plans to update this provider to use new public API?

**Comment by dmatryx** [comment]
Hey @singhalss - there are no plans to update this to the newer segment public API.
If we head down that path, we're more likely to create a whole new terraform provider due to the differences between the APIs themselves.

**Comment by kurt-lu** [comment]
Hey all- we recently added a Segment managed provider that supports Public API and a few additional resources- 

https://registry.terraform.io/providers/segmentio/segment/latest
